###
### Display
###
# Verbose program output
verbose = false

# Show progress
progress = false


###
### Runtime
###
# Number of threads to utilize.
# Defaults to number of cores available to the system if omitted.
#threads = 2

# Maximum number of allowed redirects
max_redirects = 10

### Retries

max_retries = 0

### Cache

cache = true

### Output

output = "lychee-out.md"

###
### Requests
###

# Website timeout from connect to response finished
timeout = 20

# Comma-separated list of accepted status codes for valid links.
# Omit to accept all response types.

# Accept 429 responses. They come from GitHub when you are sending too
# many requests and get throttled. They don't indicate a bad link.
# See https://github.com/lycheeverse/lychee/issues/367.
accept = "200,429"

# Proceed for server connections considered insecure (invalid TLS)
insecure = false

# Only test links with the given schemes (e.g. https)
# Omit to check links with any scheme
#scheme = [ "https" ]

# Request method
method = "get"

# Custom request headers
headers = []


###
### Exclusions
###
# Exclude URLs from checking (supports regex)
exclude = []

# Exclude URLs contained in a file from checking
# If a file named `.lycheeignore` exists in the current working directory,
# its contents will be excluded as well.
exclude_file = []

include = []

# Exclude all private IPs from checking
# Equivalent to setting `exclude_private`, `exclude_link_local`, and `exclude_loopback` to true
exclude_all_private = true

# Exclude private IP address ranges from checking
exclude_private = true

# Exclude link-local IP address range from checking
exclude_link_local = true

# Exclude loopback IP address range and localhost from checking
exclude_loopback = true

# Exclude all mail addresses from checking
exclude_mail = true
