name: Link Checker Workflow

on:
  pull_request:

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm install

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v19
        with:
          base_sha: ${{ github.event.pull_request.base.sha }}
          separator: '\n'

      - name: Wait on federalist build
        id: wait-federalist-build
        if: steps.changed-files.outputs.added_files != ''
        uses: markdboyd/wait-federalist-build-action
        with:
          DEBUG: 'true'
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}

      - name: Build website using branch-specific configuration
        if: steps.changed-files.outputs.added_files != ''
        run: |
          CI_CONFIG_FILE="_config_ci.yml"
          echo "url: ${{ steps.wait-federalist-build.outputs.preview-url }}" > $CI_CONFIG_FILE
          echo "github_branch: $GITHUB_REF" >> $CI_CONFIG_FILE
          npm run build -- --config _config.yml,$CI_CONFIG_FILE

      - name: Build website with normal configuration
        if: steps.changed-files.outputs.added_files == ''
        run: npm run build

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.4.1
        with:
          args: --github-token ${{secrets.GITHUB_TOKEN}} --max-concurrency 64 --verbose --no-progress './*.md' './_site/**/*.html'
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
