name: Link Checker Workflow

on:
  push

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build      

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.4.1
        with:
          args: --max-concurrency 64 --cache --verbose --no-progress './_site/**/*.html'
          # Temporarily don't fail CI, just run link checker
          fail: false
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
