name: Link Checker Workflow

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.4.1
        with:
          args: --max-concurrency 64 --cache
          # Temporarily don't fail CI, just run link checker
          fail: false
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
